// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void ss_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash( lv_event_t * e);
lv_obj_t *ui_Splash;
void ui_event_Image2( lv_event_t * e);
lv_obj_t *ui_Image2;
lv_obj_t *ui_Label2;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
lv_obj_t *ui_MainScreen;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label12;
lv_obj_t *ui_lblDateTime;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Switch3;
void ui_event_Switch4( lv_event_t * e);
lv_obj_t *ui_Switch4;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Label20;
lv_obj_t *ui_rollerActiveSwitchHOME;
lv_obj_t *ui_Panel18;
lv_obj_t *ui_Panel19;
lv_obj_t *ui_Panel20;
lv_obj_t *ui_lblTemperature;
lv_obj_t *ui_DateTime5;
void ui_event_Panel11( lv_event_t * e);
lv_obj_t *ui_Panel11;
lv_obj_t *ui_Label13;
void ui_event_Panel12( lv_event_t * e);
lv_obj_t *ui_Panel12;
lv_obj_t *ui_Label14;
void ui_event_Panel13( lv_event_t * e);
lv_obj_t *ui_Panel13;
lv_obj_t *ui_Label15;
void ui_event_Panel14( lv_event_t * e);
lv_obj_t *ui_Panel14;
lv_obj_t *ui_Label16;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings( lv_event_t * e);
lv_obj_t *ui_Settings;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_General;
void ui_event_swClockEnabled( lv_event_t * e);
lv_obj_t *ui_swClockEnabled;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label22;
lv_obj_t *ui_rollerWifiList;
void ui_event_txtWifiPassword( lv_event_t * e);
lv_obj_t *ui_txtWifiPassword;
lv_obj_t *ui_Keyboard2;
lv_obj_t *ui_Label23;
void ui_event_Button5( lv_event_t * e);
lv_obj_t *ui_Button5;
lv_obj_t *ui_Label29;
lv_obj_t *ui_Switch_configuration;
lv_obj_t *ui_Label24;
lv_obj_t *ui_txtSwitchName;
lv_obj_t *ui_dropListOfSwitches;
lv_obj_t *ui_Label25;
lv_obj_t *ui_txtSwitchAddress;
lv_obj_t *ui_btnAddSwitch;
lv_obj_t *ui_Label28;
lv_obj_t *ui_Label26;
lv_obj_t *ui_btnRemoveSwitch;
lv_obj_t *ui_Label27;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label30;
lv_obj_t *ui_Antenna_Configuration;
lv_obj_t *ui_Roller3;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;
lv_obj_t *ui_Label31;
lv_obj_t *ui_lblAntenna1;
lv_obj_t *ui_lblAntenna2;
lv_obj_t *ui_lblAntenna3;
lv_obj_t *ui_lblAntenna4;
void ui_event_txtAntenaName1( lv_event_t * e);
lv_obj_t *ui_txtAntenaName1;
lv_obj_t *ui_KeyboardAntenna1;
void ui_event_txtAntenaName2( lv_event_t * e);
lv_obj_t *ui_txtAntenaName2;
lv_obj_t *ui_KeyboardAntenna2;
void ui_event_txtAntenaName3( lv_event_t * e);
lv_obj_t *ui_txtAntenaName3;
lv_obj_t *ui_KeyboardAntenna3;
void ui_event_txtAntenaName4( lv_event_t * e);
lv_obj_t *ui_txtAntenaName4;
lv_obj_t *ui_KeyboardAntenna4;
lv_obj_t *ui_lblSwitchSelector;
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label32;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void ss_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom );
lv_anim_set_values(&PropertyAnimation_0, -512, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Splash( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 1500, 10000, &ui_MainScreen_screen_init);
}
}
void ui_event_Image2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1500, &ui_MainScreen_screen_init);
}
}
void ui_event_MainScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Settings_screen_init);
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Settings_screen_init);
}
}
void ui_event_Switch4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_Panel14, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Panel13, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Panel12, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
      _ui_state_modify( ui_Panel11, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
}
}
void ui_event_Panel11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_Panel12, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel13, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel14, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel11, LV_STATE_PRESSED, _UI_MODIFY_STATE_REMOVE);
}
}
void ui_event_Panel12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_Panel11, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel14, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel13, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
}
}
void ui_event_Panel13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_Panel14, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel12, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel11, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
}
}
void ui_event_Panel14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_state_modify( ui_Panel13, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel12, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
      _ui_state_modify( ui_Panel11, LV_STATE_PRESSED, _UI_MODIFY_STATE_ADD);
}
}
void ui_event_Settings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
}
}
void ui_event_swClockEnabled( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_lblDateTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}
void ui_event_txtWifiPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
}
}
void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
}
}
void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
}
}
void ui_event_txtAntenaName1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_txtAntenaName2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_txtAntenaName3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_txtAntenaName4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardAntenna4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
  //Serial.println("Inicjuje UI");
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Splash_screen_init();
ui_MainScreen_screen_init();
ui_Settings_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Splash);
}
