// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x120F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MainScreen, lv_color_hex(0x2D2828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_src( ui_MainScreen, &ui_img_logo_ei9sp_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_MainScreen, 60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_Button2, 77);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, 349 );
lv_obj_set_y( ui_Button2, -200 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, 0 );
lv_obj_set_y( ui_Label12, -1 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Settings");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x083FCD), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDateTime = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_lblDateTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblDateTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblDateTime, -311 );
lv_obj_set_y( ui_lblDateTime, -209 );
lv_obj_set_align( ui_lblDateTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblDateTime,"30/09/2023 11:58");
lv_obj_set_style_text_color(ui_lblDateTime, lv_color_hex(0xEF9412), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDateTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, 348 );
lv_obj_set_y( ui_Label17, 37 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"Lock");
lv_label_set_recolor(ui_Label17,"true");
lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xEF9412), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch3 = lv_switch_create(ui_MainScreen);
lv_obj_set_width( ui_Switch3, 80);
lv_obj_set_height( ui_Switch3, 40);
lv_obj_set_x( ui_Switch3, 351 );
lv_obj_set_y( ui_Switch3, 82 );
lv_obj_set_align( ui_Switch3, LV_ALIGN_CENTER );


ui_Switch4 = lv_switch_create(ui_MainScreen);
lv_obj_set_width( ui_Switch4, 80);
lv_obj_set_height( ui_Switch4, 40);
lv_obj_set_x( ui_Switch4, 353 );
lv_obj_set_y( ui_Switch4, -34 );
lv_obj_set_align( ui_Switch4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Switch4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Switch4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

lv_obj_set_style_shadow_color(ui_Switch4, lv_color_hex(0x503E3E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Switch4, 152, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Switch4, 1, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Switch4, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Switch4, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Switch4, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 354 );
lv_obj_set_y( ui_Label19, -75 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Disable  all");
lv_label_set_recolor(ui_Label19,"true");
lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xEF9412), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label19, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, -277 );
lv_obj_set_y( ui_Label20, 94 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"Active switch");
lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xEF9412), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rollerActiveSwitchHOME = lv_roller_create(ui_MainScreen);
lv_roller_set_options( ui_rollerActiveSwitchHOME, "Dach\nOgrodek\nShack 1\nShack 2", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_rollerActiveSwitchHOME, 100);
lv_obj_set_width( ui_rollerActiveSwitchHOME, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_rollerActiveSwitchHOME, -276 );
lv_obj_set_y( ui_rollerActiveSwitchHOME, 159 );
lv_obj_set_align( ui_rollerActiveSwitchHOME, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_rollerActiveSwitchHOME, lv_color_hex(0x7B2929), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_rollerActiveSwitchHOME, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_rollerActiveSwitchHOME, lv_color_hex(0x1E1919), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_rollerActiveSwitchHOME, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_rollerActiveSwitchHOME, lv_color_hex(0x2B0FF2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_rollerActiveSwitchHOME, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_rollerActiveSwitchHOME, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_rollerActiveSwitchHOME, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_rollerActiveSwitchHOME, lv_color_hex(0x38433A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_rollerActiveSwitchHOME, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_rollerActiveSwitchHOME, &lv_font_montserrat_18, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Panel18 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel18, 200);
lv_obj_set_height( ui_Panel18, 200);
lv_obj_set_x( ui_Panel18, -280 );
lv_obj_set_y( ui_Panel18, -26 );
lv_obj_set_align( ui_Panel18, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel18, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x070DDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Panel18, false, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel18, lv_color_hex(0x070DDE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel18, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel19 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel19, 190);
lv_obj_set_height( ui_Panel19, 190);
lv_obj_set_x( ui_Panel19, -280 );
lv_obj_set_y( ui_Panel19, -26 );
lv_obj_set_align( ui_Panel19, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel19, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xC4C3C3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Panel19, lv_color_hex(0x3D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_Panel19, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_Panel19, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_Panel19, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Panel19, false, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel19, lv_color_hex(0x38433A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel20 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel20, 140);
lv_obj_set_height( ui_Panel20, 140);
lv_obj_set_x( ui_Panel20, -280 );
lv_obj_set_y( ui_Panel20, -26 );
lv_obj_set_align( ui_Panel20, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel20, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x292020), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTemperature = lv_label_create(ui_Panel20);
lv_obj_set_width( ui_lblTemperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTemperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblTemperature, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTemperature,"23*");
lv_obj_set_style_text_color(ui_lblTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTemperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblTemperature, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lblTemperature, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblTemperature, &ui_font_Font23, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateTime5 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_DateTime5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTime5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateTime5, -280 );
lv_obj_set_y( ui_DateTime5, -145 );
lv_obj_set_align( ui_DateTime5, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateTime5,"Switch temperature");
lv_obj_set_style_text_color(ui_DateTime5, lv_color_hex(0xEF9412), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateTime5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel11 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel11, 438);
lv_obj_set_height( ui_Panel11, 100);
lv_obj_set_x( ui_Panel11, 55 );
lv_obj_set_y( ui_Panel11, -180 );
lv_obj_set_align( ui_Panel11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel11, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x1CB10F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Panel11, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x0A6515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel11, lv_color_hex(0x878181), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel11, lv_color_hex(0x38433A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel11, 125, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel11, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel11, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Panel11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Panel11, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Panel11, 200, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Panel11, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_Panel11, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x635454), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_grad_dir(ui_Panel11, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x514747), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_border_opa(ui_Panel11, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label13 = lv_label_create(ui_Panel11);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"1234567890123456");
lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel12 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel12, 438);
lv_obj_set_height( ui_Panel12, 100);
lv_obj_set_x( ui_Panel12, 55 );
lv_obj_set_y( ui_Panel12, -60 );
lv_obj_set_align( ui_Panel12, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Panel12, LV_STATE_PRESSED );     /// States
lv_obj_clear_flag( ui_Panel12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel12, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x1CB10F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Panel12, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x0A6515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel12, lv_color_hex(0x878181), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel12, lv_color_hex(0x38433A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel12, 125, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel12, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel12, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Panel12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Panel12, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Panel12, 200, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Panel12, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_Panel12, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x635454), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_grad_dir(ui_Panel12, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x514747), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label14 = lv_label_create(ui_Panel12);
lv_obj_set_width( ui_Label14, 380);
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label14,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Label14,"End FED 40-10m End FED 40-10m");
lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel13 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel13, 438);
lv_obj_set_height( ui_Panel13, 100);
lv_obj_set_x( ui_Panel13, 55 );
lv_obj_set_y( ui_Panel13, 60 );
lv_obj_set_align( ui_Panel13, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Panel13, LV_STATE_PRESSED );     /// States
lv_obj_clear_flag( ui_Panel13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel13, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x1CB10F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Panel13, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x0A6515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel13, lv_color_hex(0x878181), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel13, lv_color_hex(0x38433A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel13, 125, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel13, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel13, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Panel13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Panel13, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Panel13, 200, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Panel13, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_Panel13, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x635454), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_grad_dir(ui_Panel13, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label15 = lv_label_create(ui_Panel13);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"OffCenterDipole");
lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel14 = lv_obj_create(ui_MainScreen);
lv_obj_set_width( ui_Panel14, 438);
lv_obj_set_height( ui_Panel14, 100);
lv_obj_set_x( ui_Panel14, 55 );
lv_obj_set_y( ui_Panel14, 180 );
lv_obj_set_align( ui_Panel14, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Panel14, LV_STATE_PRESSED );     /// States
lv_obj_clear_flag( ui_Panel14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel14, 25, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x1CB10F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Panel14, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x0A6515), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel14, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Panel14, lv_color_hex(0x878181), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Panel14, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Panel14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel14, lv_color_hex(0x38433A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel14, 125, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel14, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel14, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_Panel14, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_Panel14, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Panel14, 200, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_Panel14, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xE31C1C), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x7E0101), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_Panel14, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x635454), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_bg_grad_dir(ui_Panel14, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x514747), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_Label16 = lv_label_create(ui_Panel14);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"DoubleBazooka 6");
lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_42, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel11, ui_event_Panel11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel12, ui_event_Panel12, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel13, ui_event_Panel13, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Panel14, ui_event_Panel14, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
