// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void ss_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_lblDateTime;
extern lv_obj_t * ui_Label17;
void ui_event_LockSwitch(lv_event_t * e);
extern lv_obj_t * ui_LockSwitch;
void ui_event_DisableAllSwitch(lv_event_t * e);
extern lv_obj_t * ui_DisableAllSwitch;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
void ui_event_rollerActiveSwitchHOME(lv_event_t * e);
extern lv_obj_t * ui_rollerActiveSwitchHOME;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_lblTemperature;
extern lv_obj_t * ui_DateTime5;
void ui_event_Panel11(lv_event_t * e);
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Antenna1Label;
void ui_event_Panel12(lv_event_t * e);
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Antenna2Label;
void ui_event_Panel13(lv_event_t * e);
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Antenna3Label;
void ui_event_Panel14(lv_event_t * e);
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Antenna4Label;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_General;
void ui_event_swClockEnabled(lv_event_t * e);
extern lv_obj_t * ui_swClockEnabled;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label22;
void ui_event_rollerWifiList(lv_event_t * e);
extern lv_obj_t * ui_rollerWifiList;
void ui_event_txtWifiPassword(lv_event_t * e);
extern lv_obj_t * ui_txtWifiPassword;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label23;
void ui_event_SettingsButtonGeneral(lv_event_t * e);
extern lv_obj_t * ui_SettingsButtonGeneral;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_ntpDropdown;
void ui_event_connectButton(lv_event_t * e);
extern lv_obj_t * ui_connectButton;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Switch_configuration;
extern lv_obj_t * ui_Label24;
void ui_event_txtSwitchName(lv_event_t * e);
extern lv_obj_t * ui_txtSwitchName;
extern lv_obj_t * ui_dropListOfSwitches;
extern lv_obj_t * ui_Label25;
void ui_event_txtSwitchAddress(lv_event_t * e);
extern lv_obj_t * ui_txtSwitchAddress;
extern lv_obj_t * ui_btnAddSwitch;
void ui_event_Label28(lv_event_t * e);
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_btnRemoveSwitch;
void ui_event_Label27(lv_event_t * e);
extern lv_obj_t * ui_Label27;
void ui_event_HomeButtonSwitch(lv_event_t * e);
extern lv_obj_t * ui_HomeButtonSwitch;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_swNameKeyboard;
extern lv_obj_t * ui_swAddrKeyboard;
extern lv_obj_t * ui_Antenna_Configuration;
void ui_event_SwitchRoller(lv_event_t * e);
extern lv_obj_t * ui_SwitchRoller;
void ui_event_HomeButtonAntenna(lv_event_t * e);
extern lv_obj_t * ui_HomeButtonAntenna;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_lblAntenna1;
extern lv_obj_t * ui_lblAntenna2;
extern lv_obj_t * ui_lblAntenna3;
extern lv_obj_t * ui_lblAntenna4;
void ui_event_txtAntenaName1(lv_event_t * e);
extern lv_obj_t * ui_txtAntenaName1;
extern lv_obj_t * ui_KeyboardAntenna1;
void ui_event_txtAntenaName2(lv_event_t * e);
extern lv_obj_t * ui_txtAntenaName2;
extern lv_obj_t * ui_KeyboardAntenna2;
void ui_event_txtAntenaName3(lv_event_t * e);
extern lv_obj_t * ui_txtAntenaName3;
extern lv_obj_t * ui_KeyboardAntenna3;
void ui_event_txtAntenaName4(lv_event_t * e);
extern lv_obj_t * ui_txtAntenaName4;
extern lv_obj_t * ui_KeyboardAntenna4;
extern lv_obj_t * ui_lblSwitchSelector;
void ui_event_SaveSettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SaveSettingsButton;
extern lv_obj_t * ui_Label32;
void ui_event_msgPanelSettingsGeneral(lv_event_t * e);
extern lv_obj_t * ui_msgPanelSettingsGeneral;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_msgLabelGeneral;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_logo_ei9spc_png);    // assets\logo_ei9spc.png
LV_IMG_DECLARE(ui_img_logo_ei9sp_png);    // assets\logo_ei9sp.png

LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font23);
LV_FONT_DECLARE(ui_font_Font80);
LV_FONT_DECLARE(ui_font_Font801);
LV_FONT_DECLARE(ui_font_LightsOut40);
LV_FONT_DECLARE(ui_font_LightsOut60);
LV_FONT_DECLARE(ui_font_LightsOut80);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
