// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
//#include <Arduino.h>

void removeSwitch(lv_event_t* e) {
  // Your code here
}

void saveAntennaConfiguration(lv_event_t* e) {
  // Your code here
}

void LockSwitchChanged(lv_event_t* e) {
  // Your code here
}

void DisableAllChanged(lv_event_t* e) {
  // Your code here
}

void ActiveSwitchChanged(lv_event_t* e) {
  // Your code here
}

void A1ButtonClicked(lv_event_t* e) {
  // Your code here
}

void A2ButtonClicked(lv_event_t* e) {
  // Your code here
}

void A3ButtonClicked(lv_event_t* e) {
  // Your code here
}

void A4ButtonClicked(lv_event_t* e) {
  // Your code here
}

void LoadMainScreenValues(lv_event_t* e) {
  // Your code here
}

void UpdateTemp(lv_event_t* e) {
  // Your code here
}
/*
void WiFiLoadScreen(lv_event_t * e)
{
	// Your code here
}
*/
void SetWifiPassword(lv_event_t* e) {
  // Your code here
}

void NTPServerChanged(lv_event_t* e) {
  // Your code here
}

void UpdateSwitchList(lv_event_t* e) {
  // Your code here
}

void SwitchnameUpdated(lv_event_t* e) {
  // Your code here
}

void SwitchLisyChanged(lv_event_t* e) {
  // Your code here
}

void SwitchAddressUpdated(lv_event_t* e) {
  // Your code here
}

void AddSwitch(lv_event_t* e) {
  // Your code here
}

void RemoveSwitch(lv_event_t* e) {
  // Your code here
}

void Ant1NameChanged(lv_event_t* e) {
  // Your code here
}

void Ant2NameChanged(lv_event_t* e) {
  // Your code here
}

void Ant3NameChanged(lv_event_t* e) {
  // Your code here
}

void Ant4NameChanged(lv_event_t* e) {
  // Your code here
}

void SaveSwitchAntennas(lv_event_t* e) {
  // Your code here
}

void ConnectSelectedWifi(lv_event_t* e) {
  // Your code here
}

void lockClicked(lv_event_t* e) {
  // Your code here
}

void disableAllClicked(lv_event_t* e) {
  // Your code here
}

void activeSwitchChanged(lv_event_t* e) {
  // Your code here
}
/*
void ant1Clicked(lv_event_t * e)
{
	// Your code here
}

void ant2Clicked(lv_event_t * e)
{
	// Your code here
}

void ant3Clicked(lv_event_t * e)
{
	// Your code here
}

void ant4Clicked(lv_event_t * e)
{
	// Your code here
}
*/


/*
void connectWiFI(lv_event_t * e)
{
	// Your code here
}
*/
void addNewSwitch(lv_event_t* e) {
  // Your code here
}

void antSwitchChanged(lv_event_t* e) {
  // Your code here
}
