// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void lockClicked(lv_event_t * e);
void disableAllClicked(lv_event_t * e);
void activeSwitchChanged(lv_event_t * e);
void ant1Clicked(lv_event_t * e);
void ant2Clicked(lv_event_t * e);
void ant3Clicked(lv_event_t * e);
void ant4Clicked(lv_event_t * e);
void setNTPServer(lv_event_t * e);
void wifiScrollChanged(lv_event_t * e);
void connectWiFI(lv_event_t * e);
void addNewSwitch(lv_event_t * e);
void removeSwitch(lv_event_t * e);
void antSwitchChanged(lv_event_t * e);
void saveAntennaConfiguration(lv_event_t * e);
void WiFiLoadScreen(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
