// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Settings, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x120F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Settings, LV_DIR_TOP, 50);
    lv_obj_set_height(ui_TabView1, 463);
    lv_obj_set_width(ui_TabView1, lv_pct(99));
    lv_obj_set_x(ui_TabView1, 2);
    lv_obj_set_y(ui_TabView1, 2);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x120F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_General = lv_tabview_add_tab(ui_TabView1, "General");
    lv_obj_clear_flag(ui_General, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_General, LV_SCROLLBAR_MODE_OFF);

    ui_swClockEnabled = lv_switch_create(ui_General);
    lv_obj_set_width(ui_swClockEnabled, 50);
    lv_obj_set_height(ui_swClockEnabled, 25);
    lv_obj_set_x(ui_swClockEnabled, 575);
    lv_obj_set_y(ui_swClockEnabled, 0);


    ui_Label18 = lv_label_create(ui_General);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 430);
    lv_obj_set_y(ui_Label18, 5);
    lv_label_set_text(ui_Label18, "Clock enabled");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_General);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 434);
    lv_obj_set_y(ui_Label3, 59);
    lv_label_set_text(ui_Label3, "NTP");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_General);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -20);
    lv_obj_set_y(ui_Label22, 31);
    lv_label_set_text(ui_Label22, "SSID");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerWifiList = lv_roller_create(ui_General);
    lv_roller_set_options(ui_rollerWifiList, "WifiHome\nAlfa\nBeta\nSiecSasiada\nEircom43872", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_rollerWifiList, 100);
    lv_obj_set_width(ui_rollerWifiList, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_rollerWifiList, -235);
    lv_obj_set_y(ui_rollerWifiList, -146);
    lv_obj_set_align(ui_rollerWifiList, LV_ALIGN_CENTER);

    ui_txtWifiPassword = lv_textarea_create(ui_General);
    lv_obj_set_width(ui_txtWifiPassword, 286);
    lv_obj_set_height(ui_txtWifiPassword, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_txtWifiPassword, -163);
    lv_obj_set_y(ui_txtWifiPassword, -63);
    lv_obj_set_align(ui_txtWifiPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtWifiPassword, "Placeholder...");
    lv_textarea_set_one_line(ui_txtWifiPassword, true);
    lv_textarea_set_password_mode(ui_txtWifiPassword, true);



    ui_Keyboard2 = lv_keyboard_create(ui_General);
    lv_obj_set_width(ui_Keyboard2, 768);
    lv_obj_set_height(ui_Keyboard2, 190);
    lv_obj_set_x(ui_Keyboard2, -8);
    lv_obj_set_y(ui_Keyboard2, 91);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Label23 = lv_label_create(ui_General);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -16);
    lv_obj_set_y(ui_Label23, 112);
    lv_label_set_text(ui_Label23, "Password");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonGeneral = lv_btn_create(ui_General);
    lv_obj_set_width(ui_SettingsButtonGeneral, 70);
    lv_obj_set_height(ui_SettingsButtonGeneral, 34);
    lv_obj_set_x(ui_SettingsButtonGeneral, 338);
    lv_obj_set_y(ui_SettingsButtonGeneral, -174);
    lv_obj_set_align(ui_SettingsButtonGeneral, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonGeneral, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButtonGeneral, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButtonGeneral, lv_color_hex(0xC73838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButtonGeneral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_SettingsButtonGeneral);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "HOME");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xF5EE0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ntpDropdown = lv_dropdown_create(ui_General);
    lv_dropdown_set_options(ui_ntpDropdown, "Worldwide\nEurope\nAsia\nOceania\nNorth America\nSouth America");
    lv_obj_set_width(ui_ntpDropdown, 150);
    lv_obj_set_height(ui_ntpDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ntpDropdown, 190);
    lv_obj_set_y(ui_ntpDropdown, -117);
    lv_obj_set_align(ui_ntpDropdown, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ntpDropdown, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_ntpDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ntpDropdown, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_ntpDropdown, 255, LV_PART_MAIN | LV_STATE_DISABLED);



    ui_connectButton = lv_btn_create(ui_General);
    lv_obj_set_width(ui_connectButton, 100);
    lv_obj_set_height(ui_connectButton, 84);
    lv_obj_set_x(ui_connectButton, -75);
    lv_obj_set_y(ui_connectButton, -146);
    lv_obj_set_align(ui_connectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_connectButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Connect");

    ui_Switch_configuration = lv_tabview_add_tab(ui_TabView1, "Switch configuration");
    lv_obj_clear_flag(ui_Switch_configuration,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Switch_configuration, LV_SCROLLBAR_MODE_OFF);

    ui_Label24 = lv_label_create(ui_Switch_configuration);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -328);
    lv_obj_set_y(ui_Label24, -141);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Switch name");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSwitchName = lv_textarea_create(ui_Switch_configuration);
    lv_obj_set_width(ui_txtSwitchName, 254);
    lv_obj_set_height(ui_txtSwitchName, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_txtSwitchName, -104);
    lv_obj_set_y(ui_txtSwitchName, -143);
    lv_obj_set_align(ui_txtSwitchName, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtSwitchName, "Placeholder...");
    lv_textarea_set_one_line(ui_txtSwitchName, true);



    ui_dropListOfSwitches = lv_dropdown_create(ui_Switch_configuration);
    lv_obj_set_width(ui_dropListOfSwitches, 254);
    lv_obj_set_height(ui_dropListOfSwitches, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dropListOfSwitches, -105);
    lv_obj_set_y(ui_dropListOfSwitches, -20);
    lv_obj_set_align(ui_dropListOfSwitches, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropListOfSwitches, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Label25 = lv_label_create(ui_Switch_configuration);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -322);
    lv_obj_set_y(ui_Label25, -77);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Switch address");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtSwitchAddress = lv_textarea_create(ui_Switch_configuration);
    lv_obj_set_width(ui_txtSwitchAddress, 254);
    lv_obj_set_height(ui_txtSwitchAddress, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_x(ui_txtSwitchAddress, -103);
    lv_obj_set_y(ui_txtSwitchAddress, -82);
    lv_obj_set_align(ui_txtSwitchAddress, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtSwitchAddress, "Placeholder...");
    lv_textarea_set_one_line(ui_txtSwitchAddress, true);



    ui_btnAddSwitch = lv_btn_create(ui_Switch_configuration);
    lv_obj_set_width(ui_btnAddSwitch, 137);
    lv_obj_set_height(ui_btnAddSwitch, 85);
    lv_obj_set_x(ui_btnAddSwitch, 186);
    lv_obj_set_y(ui_btnAddSwitch, -113);
    lv_obj_set_align(ui_btnAddSwitch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnAddSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnAddSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_btnAddSwitch);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Add switch");

    ui_Label26 = lv_label_create(ui_Switch_configuration);
    lv_obj_set_width(ui_Label26, 135);
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -300);
    lv_obj_set_y(ui_Label26, -13);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "List of recorded switches ");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRemoveSwitch = lv_btn_create(ui_Switch_configuration);
    lv_obj_set_width(ui_btnRemoveSwitch, 137);
    lv_obj_set_height(ui_btnRemoveSwitch, 55);
    lv_obj_set_x(ui_btnRemoveSwitch, 187);
    lv_obj_set_y(ui_btnRemoveSwitch, -22);
    lv_obj_set_align(ui_btnRemoveSwitch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRemoveSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnRemoveSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_btnRemoveSwitch);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Remove selected");

    ui_HomeButtonSwitch = lv_btn_create(ui_Switch_configuration);
    lv_obj_set_width(ui_HomeButtonSwitch, 70);
    lv_obj_set_height(ui_HomeButtonSwitch, 34);
    lv_obj_set_x(ui_HomeButtonSwitch, 338);
    lv_obj_set_y(ui_HomeButtonSwitch, -174);
    lv_obj_set_align(ui_HomeButtonSwitch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonSwitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButtonSwitch, lv_color_hex(0xC73838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_HomeButtonSwitch);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "HOME");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xF5EE0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swNameKeyboard = lv_keyboard_create(ui_Switch_configuration);
    lv_obj_set_width(ui_swNameKeyboard, 737);
    lv_obj_set_height(ui_swNameKeyboard, 185);
    lv_obj_set_x(ui_swNameKeyboard, -6);
    lv_obj_set_y(ui_swNameKeyboard, 101);
    lv_obj_set_align(ui_swNameKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_swNameKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_swAddrKeyboard = lv_keyboard_create(ui_Switch_configuration);
    lv_keyboard_set_mode(ui_swAddrKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_swAddrKeyboard, 737);
    lv_obj_set_height(ui_swAddrKeyboard, 185);
    lv_obj_set_x(ui_swAddrKeyboard, -6);
    lv_obj_set_y(ui_swAddrKeyboard, 101);
    lv_obj_set_align(ui_swAddrKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_swAddrKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Antenna_Configuration = lv_tabview_add_tab(ui_TabView1, "Antenna Configuration");
    lv_obj_clear_flag(ui_Antenna_Configuration,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Antenna_Configuration, LV_SCROLLBAR_MODE_OFF);

    ui_SwitchRoller = lv_roller_create(ui_Antenna_Configuration);
    lv_roller_set_options(ui_SwitchRoller, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_SwitchRoller, 100);
    lv_obj_set_width(ui_SwitchRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_SwitchRoller, 208);
    lv_obj_set_y(ui_SwitchRoller, -100);
    lv_obj_set_align(ui_SwitchRoller, LV_ALIGN_CENTER);

    ui_HomeButtonAntenna = lv_btn_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_HomeButtonAntenna, 70);
    lv_obj_set_height(ui_HomeButtonAntenna, 34);
    lv_obj_set_x(ui_HomeButtonAntenna, 338);
    lv_obj_set_y(ui_HomeButtonAntenna, -174);
    lv_obj_set_align(ui_HomeButtonAntenna, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeButtonAntenna, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeButtonAntenna, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeButtonAntenna, lv_color_hex(0xC73838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeButtonAntenna, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_HomeButtonAntenna);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "HOME");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xF5EE0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAntenna1 = lv_label_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_lblAntenna1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAntenna1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAntenna1, -307);
    lv_obj_set_y(ui_lblAntenna1, -170);
    lv_obj_set_align(ui_lblAntenna1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAntenna1, "Name of antena #1");
    lv_obj_set_style_text_color(ui_lblAntenna1, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAntenna1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAntenna2 = lv_label_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_lblAntenna2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAntenna2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAntenna2, -313);
    lv_obj_set_y(ui_lblAntenna2, -120);
    lv_obj_set_align(ui_lblAntenna2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAntenna2, "Name of antena #2");
    lv_obj_set_style_text_color(ui_lblAntenna2, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAntenna2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAntenna3 = lv_label_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_lblAntenna3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAntenna3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAntenna3, -311);
    lv_obj_set_y(ui_lblAntenna3, -70);
    lv_obj_set_align(ui_lblAntenna3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAntenna3, "Name of antena #3");
    lv_obj_set_style_text_color(ui_lblAntenna3, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAntenna3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAntenna4 = lv_label_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_lblAntenna4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAntenna4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAntenna4, -312);
    lv_obj_set_y(ui_lblAntenna4, -20);
    lv_obj_set_align(ui_lblAntenna4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAntenna4, "Name of antena #4");
    lv_obj_set_style_text_color(ui_lblAntenna4, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAntenna4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtAntenaName1 = lv_textarea_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_txtAntenaName1, 338);
    lv_obj_set_height(ui_txtAntenaName1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_txtAntenaName1, -53);
    lv_obj_set_y(ui_txtAntenaName1, -170);
    lv_obj_set_align(ui_txtAntenaName1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtAntenaName1, "Antenna 1");
    lv_textarea_set_placeholder_text(ui_txtAntenaName1, "Placeholder...");
    lv_textarea_set_one_line(ui_txtAntenaName1, true);



    ui_KeyboardAntenna1 = lv_keyboard_create(ui_Antenna_Configuration);
    lv_keyboard_set_mode(ui_KeyboardAntenna1, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_KeyboardAntenna1, 720);
    lv_obj_set_height(ui_KeyboardAntenna1, 179);
    lv_obj_set_x(ui_KeyboardAntenna1, -14);
    lv_obj_set_y(ui_KeyboardAntenna1, 109);
    lv_obj_set_align(ui_KeyboardAntenna1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardAntenna1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_txtAntenaName2 = lv_textarea_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_txtAntenaName2, 338);
    lv_obj_set_height(ui_txtAntenaName2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_txtAntenaName2, -53);
    lv_obj_set_y(ui_txtAntenaName2, -120);
    lv_obj_set_align(ui_txtAntenaName2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtAntenaName2, "Antenna 2");
    lv_textarea_set_placeholder_text(ui_txtAntenaName2, "Placeholder...");
    lv_textarea_set_one_line(ui_txtAntenaName2, true);



    ui_KeyboardAntenna2 = lv_keyboard_create(ui_Antenna_Configuration);
    lv_keyboard_set_mode(ui_KeyboardAntenna2, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_KeyboardAntenna2, 720);
    lv_obj_set_height(ui_KeyboardAntenna2, 179);
    lv_obj_set_x(ui_KeyboardAntenna2, -14);
    lv_obj_set_y(ui_KeyboardAntenna2, 109);
    lv_obj_set_align(ui_KeyboardAntenna2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardAntenna2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_txtAntenaName3 = lv_textarea_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_txtAntenaName3, 338);
    lv_obj_set_height(ui_txtAntenaName3, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_txtAntenaName3, -53);
    lv_obj_set_y(ui_txtAntenaName3, -70);
    lv_obj_set_align(ui_txtAntenaName3, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtAntenaName3, "Antenna 3");
    lv_textarea_set_placeholder_text(ui_txtAntenaName3, "Placeholder...");
    lv_textarea_set_one_line(ui_txtAntenaName3, true);



    ui_KeyboardAntenna3 = lv_keyboard_create(ui_Antenna_Configuration);
    lv_keyboard_set_mode(ui_KeyboardAntenna3, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_KeyboardAntenna3, 720);
    lv_obj_set_height(ui_KeyboardAntenna3, 179);
    lv_obj_set_x(ui_KeyboardAntenna3, -14);
    lv_obj_set_y(ui_KeyboardAntenna3, 109);
    lv_obj_set_align(ui_KeyboardAntenna3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardAntenna3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_txtAntenaName4 = lv_textarea_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_txtAntenaName4, 338);
    lv_obj_set_height(ui_txtAntenaName4, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_txtAntenaName4, -53);
    lv_obj_set_y(ui_txtAntenaName4, -20);
    lv_obj_set_align(ui_txtAntenaName4, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_txtAntenaName4, "Antenna 4");
    lv_textarea_set_placeholder_text(ui_txtAntenaName4, "Placeholder...");
    lv_textarea_set_one_line(ui_txtAntenaName4, true);



    ui_KeyboardAntenna4 = lv_keyboard_create(ui_Antenna_Configuration);
    lv_keyboard_set_mode(ui_KeyboardAntenna4, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_KeyboardAntenna4, 720);
    lv_obj_set_height(ui_KeyboardAntenna4, 179);
    lv_obj_set_x(ui_KeyboardAntenna4, -14);
    lv_obj_set_y(ui_KeyboardAntenna4, 109);
    lv_obj_set_align(ui_KeyboardAntenna4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KeyboardAntenna4, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_lblSwitchSelector = lv_label_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_lblSwitchSelector, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSwitchSelector, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSwitchSelector, 209);
    lv_obj_set_y(ui_lblSwitchSelector, -170);
    lv_obj_set_align(ui_lblSwitchSelector, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSwitchSelector, "Select switch");
    lv_obj_set_style_text_color(ui_lblSwitchSelector, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSwitchSelector, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveSettingsButton = lv_btn_create(ui_Antenna_Configuration);
    lv_obj_set_width(ui_SaveSettingsButton, 166);
    lv_obj_set_height(ui_SaveSettingsButton, 33);
    lv_obj_set_x(ui_SaveSettingsButton, 269);
    lv_obj_set_y(ui_SaveSettingsButton, -17);
    lv_obj_set_align(ui_SaveSettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_SaveSettingsButton);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Save settings");

    ui_msgPanelSettingsGeneral = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_msgPanelSettingsGeneral, 522);
    lv_obj_set_height(ui_msgPanelSettingsGeneral, 169);
    lv_obj_set_x(ui_msgPanelSettingsGeneral, -15);
    lv_obj_set_y(ui_msgPanelSettingsGeneral, -39);
    lv_obj_set_align(ui_msgPanelSettingsGeneral, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_msgPanelSettingsGeneral, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_msgPanelSettingsGeneral, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_msgPanelSettingsGeneral, lv_color_hex(0x0F1DCA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_msgPanelSettingsGeneral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_msgPanelSettingsGeneral, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_msgPanelSettingsGeneral, lv_color_hex(0xAF1010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_msgPanelSettingsGeneral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_msgPanelSettingsGeneral, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_msgPanelSettingsGeneral);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -2);
    lv_obj_set_y(ui_Label4, 70);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "TOUCH TO CLOSE THIS WINDOW");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xAF1010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_msgLabelGeneral = lv_label_create(ui_msgPanelSettingsGeneral);
    lv_obj_set_width(ui_msgLabelGeneral, 445);
    lv_obj_set_height(ui_msgLabelGeneral, 124);
    lv_obj_set_x(ui_msgLabelGeneral, -1);
    lv_obj_set_y(ui_msgLabelGeneral, -9);
    lv_obj_set_align(ui_msgLabelGeneral, LV_ALIGN_CENTER);
    lv_label_set_text(ui_msgLabelGeneral, "This \nis \na\nmessage \npoput window");
    lv_obj_set_style_text_color(ui_msgLabelGeneral, lv_color_hex(0x538087), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_msgLabelGeneral, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_msgLabelGeneral, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_msgLabelGeneral, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_swClockEnabled, ui_event_swClockEnabled, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rollerWifiList, ui_event_rollerWifiList, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtWifiPassword, ui_event_txtWifiPassword, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_txtWifiPassword);
    lv_obj_add_event_cb(ui_SettingsButtonGeneral, ui_event_SettingsButtonGeneral, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_connectButton, ui_event_connectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtSwitchName, ui_event_txtSwitchName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtSwitchAddress, ui_event_txtSwitchAddress, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label28, ui_event_Label28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label27, ui_event_Label27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButtonSwitch, ui_event_HomeButtonSwitch, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_swNameKeyboard, ui_txtSwitchName);
    lv_keyboard_set_textarea(ui_swAddrKeyboard, ui_txtSwitchAddress);
    lv_obj_add_event_cb(ui_SwitchRoller, ui_event_SwitchRoller, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeButtonAntenna, ui_event_HomeButtonAntenna, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_txtAntenaName1, ui_event_txtAntenaName1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardAntenna1, ui_txtAntenaName1);
    lv_obj_add_event_cb(ui_txtAntenaName2, ui_event_txtAntenaName2, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardAntenna2, ui_txtAntenaName2);
    lv_obj_add_event_cb(ui_txtAntenaName3, ui_event_txtAntenaName3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardAntenna3, ui_txtAntenaName3);
    lv_obj_add_event_cb(ui_txtAntenaName4, ui_event_txtAntenaName4, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardAntenna4, ui_txtAntenaName4);
    lv_obj_add_event_cb(ui_SaveSettingsButton, ui_event_SaveSettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_msgPanelSettingsGeneral, ui_event_msgPanelSettingsGeneral, LV_EVENT_ALL, NULL);

}
