// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"

void ui_Splash_screen_init(void)
{
ui_Splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0x120F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Splash);
lv_img_set_src(ui_Image2, &ui_img_logo_ei9spc_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 392
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 390
lv_obj_set_x( ui_Image2, 0 );
lv_obj_set_y( ui_Image2, -30 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Splash);
lv_obj_set_width( ui_Label2, 650);
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Label2, 6 );
lv_obj_set_y( ui_Label2, 189 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label2,LV_LABEL_LONG_SCROLL);
lv_label_set_text(ui_Label2,"Antenna  switch by EI9SP. All rights reserverd 2023/");
lv_obj_set_scrollbar_mode(ui_Label2, LV_SCROLLBAR_MODE_ACTIVE);
lv_obj_set_scroll_dir(ui_Label2, LV_DIR_LEFT);
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xA10BA3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_Font23, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
