// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#include "ui.h"

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x120F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView1 = lv_tabview_create(ui_Settings, LV_DIR_TOP, 50);
lv_obj_set_height( ui_TabView1, 463);
lv_obj_set_width( ui_TabView1, lv_pct(99));
lv_obj_set_x( ui_TabView1, 2 );
lv_obj_set_y( ui_TabView1, 2 );
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0x120F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TabView1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


ui_General = lv_tabview_add_tab(ui_TabView1, "General");

ui_swClockEnabled = lv_switch_create(ui_General);
lv_obj_set_width( ui_swClockEnabled, 50);
lv_obj_set_height( ui_swClockEnabled, 25);
lv_obj_set_x( ui_swClockEnabled, 135 );
lv_obj_set_y( ui_swClockEnabled, -5 );


ui_Label18 = lv_label_create(ui_General);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label18,"Clock enabled");
lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_General);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label22, 9 );
lv_obj_set_y( ui_Label22, 70 );
lv_label_set_text(ui_Label22,"Wifi ID");
lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rollerWifiList = lv_roller_create(ui_General);
lv_roller_set_options( ui_rollerWifiList, "WifiHome\nAlfa\nBeta\nSiecSasiada\nEircom43872", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_rollerWifiList, 100);
lv_obj_set_width( ui_rollerWifiList, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_rollerWifiList, -216 );
lv_obj_set_y( ui_rollerWifiList, -104 );
lv_obj_set_align( ui_rollerWifiList, LV_ALIGN_CENTER );

ui_txtWifiPassword = lv_textarea_create(ui_General);
lv_obj_set_width( ui_txtWifiPassword, 286);
lv_obj_set_height( ui_txtWifiPassword, LV_SIZE_CONTENT);   /// 34
lv_obj_set_x( ui_txtWifiPassword, 180 );
lv_obj_set_y( ui_txtWifiPassword, -103 );
lv_obj_set_align( ui_txtWifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_txtWifiPassword,"Placeholder...");
lv_textarea_set_one_line(ui_txtWifiPassword,true);
lv_textarea_set_password_mode(ui_txtWifiPassword, true);



ui_Keyboard2 = lv_keyboard_create(ui_General);
lv_obj_set_width( ui_Keyboard2, 768);
lv_obj_set_height( ui_Keyboard2, 190);
lv_obj_set_x( ui_Keyboard2, -8 );
lv_obj_set_y( ui_Keyboard2, 91 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Keyboard2, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_Label23 = lv_label_create(ui_General);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, 267 );
lv_obj_set_y( ui_Label23, 71 );
lv_label_set_text(ui_Label23,"Wifi Ipassword");
lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_btn_create(ui_General);
lv_obj_set_width( ui_Button5, 70);
lv_obj_set_height( ui_Button5, 34);
lv_obj_set_x( ui_Button5, 338 );
lv_obj_set_y( ui_Button5, -174 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xC73838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label29 = lv_label_create(ui_Button5);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"HOME");
lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xF5EE0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch_configuration = lv_tabview_add_tab(ui_TabView1, "Switch configuration");

ui_Label24 = lv_label_create(ui_Switch_configuration);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, -328 );
lv_obj_set_y( ui_Label24, -141 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"Switch name");
lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtSwitchName = lv_textarea_create(ui_Switch_configuration);
lv_obj_set_width( ui_txtSwitchName, 254);
lv_obj_set_height( ui_txtSwitchName, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_txtSwitchName, -104 );
lv_obj_set_y( ui_txtSwitchName, -143 );
lv_obj_set_align( ui_txtSwitchName, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_txtSwitchName,"Placeholder...");
lv_textarea_set_one_line(ui_txtSwitchName,true);



ui_dropListOfSwitches = lv_dropdown_create(ui_Switch_configuration);
lv_obj_set_width( ui_dropListOfSwitches, 221);
lv_obj_set_height( ui_dropListOfSwitches, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dropListOfSwitches, -53 );
lv_obj_set_y( ui_dropListOfSwitches, -2 );
lv_obj_set_align( ui_dropListOfSwitches, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dropListOfSwitches, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_Label25 = lv_label_create(ui_Switch_configuration);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, -322 );
lv_obj_set_y( ui_Label25, -77 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Switch address");
lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtSwitchAddress = lv_textarea_create(ui_Switch_configuration);
lv_obj_set_width( ui_txtSwitchAddress, 254);
lv_obj_set_height( ui_txtSwitchAddress, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_txtSwitchAddress, -106 );
lv_obj_set_y( ui_txtSwitchAddress, -78 );
lv_obj_set_align( ui_txtSwitchAddress, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_txtSwitchAddress,"Placeholder...");
lv_textarea_set_one_line(ui_txtSwitchAddress,true);



ui_btnAddSwitch = lv_btn_create(ui_Switch_configuration);
lv_obj_set_width( ui_btnAddSwitch, 137);
lv_obj_set_height( ui_btnAddSwitch, 85);
lv_obj_set_x( ui_btnAddSwitch, 186 );
lv_obj_set_y( ui_btnAddSwitch, -113 );
lv_obj_set_align( ui_btnAddSwitch, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnAddSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnAddSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label28 = lv_label_create(ui_btnAddSwitch);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"Add switch");

ui_Label26 = lv_label_create(ui_Switch_configuration);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, -276 );
lv_obj_set_y( ui_Label26, -2 );
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"List of recorded switches ");
lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_btnRemoveSwitch = lv_btn_create(ui_Switch_configuration);
lv_obj_set_width( ui_btnRemoveSwitch, 137);
lv_obj_set_height( ui_btnRemoveSwitch, 55);
lv_obj_set_x( ui_btnRemoveSwitch, 185 );
lv_obj_set_y( ui_btnRemoveSwitch, -2 );
lv_obj_set_align( ui_btnRemoveSwitch, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnRemoveSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnRemoveSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label27 = lv_label_create(ui_btnRemoveSwitch);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"Remove selected");

ui_Button6 = lv_btn_create(ui_Switch_configuration);
lv_obj_set_width( ui_Button6, 70);
lv_obj_set_height( ui_Button6, 34);
lv_obj_set_x( ui_Button6, 338 );
lv_obj_set_y( ui_Button6, -174 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xC73838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label30 = lv_label_create(ui_Button6);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"HOME");
lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xF5EE0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Antenna_Configuration = lv_tabview_add_tab(ui_TabView1, "Antenna Configuration");

ui_Roller3 = lv_roller_create(ui_Antenna_Configuration);
lv_roller_set_options( ui_Roller3, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller3, 100);
lv_obj_set_width( ui_Roller3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller3, 209 );
lv_obj_set_y( ui_Roller3, -100 );
lv_obj_set_align( ui_Roller3, LV_ALIGN_CENTER );

ui_Button7 = lv_btn_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_Button7, 70);
lv_obj_set_height( ui_Button7, 34);
lv_obj_set_x( ui_Button7, 338 );
lv_obj_set_y( ui_Button7, -174 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xC73838), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label31 = lv_label_create(ui_Button7);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"HOME");
lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xF5EE0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblAntenna1 = lv_label_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_lblAntenna1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblAntenna1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblAntenna1, -307 );
lv_obj_set_y( ui_lblAntenna1, -170 );
lv_obj_set_align( ui_lblAntenna1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblAntenna1,"Name of antena #1");
lv_obj_set_style_text_color(ui_lblAntenna1, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblAntenna1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblAntenna2 = lv_label_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_lblAntenna2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblAntenna2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblAntenna2, -313 );
lv_obj_set_y( ui_lblAntenna2, -120 );
lv_obj_set_align( ui_lblAntenna2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblAntenna2,"Name of antena #2");
lv_obj_set_style_text_color(ui_lblAntenna2, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblAntenna2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblAntenna3 = lv_label_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_lblAntenna3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblAntenna3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblAntenna3, -311 );
lv_obj_set_y( ui_lblAntenna3, -70 );
lv_obj_set_align( ui_lblAntenna3, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblAntenna3,"Name of antena #3");
lv_obj_set_style_text_color(ui_lblAntenna3, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblAntenna3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblAntenna4 = lv_label_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_lblAntenna4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblAntenna4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblAntenna4, -312 );
lv_obj_set_y( ui_lblAntenna4, -20 );
lv_obj_set_align( ui_lblAntenna4, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblAntenna4,"Name of antena #4");
lv_obj_set_style_text_color(ui_lblAntenna4, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblAntenna4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_txtAntenaName1 = lv_textarea_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_txtAntenaName1, 338);
lv_obj_set_height( ui_txtAntenaName1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_txtAntenaName1, -53 );
lv_obj_set_y( ui_txtAntenaName1, -170 );
lv_obj_set_align( ui_txtAntenaName1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_txtAntenaName1,"Antenna 1");
lv_textarea_set_placeholder_text(ui_txtAntenaName1,"Placeholder...");
lv_textarea_set_one_line(ui_txtAntenaName1,true);



ui_KeyboardAntenna1 = lv_keyboard_create(ui_Antenna_Configuration);
lv_keyboard_set_mode(ui_KeyboardAntenna1,LV_KEYBOARD_MODE_TEXT_UPPER);
lv_obj_set_width( ui_KeyboardAntenna1, 720);
lv_obj_set_height( ui_KeyboardAntenna1, 179);
lv_obj_set_x( ui_KeyboardAntenna1, -14 );
lv_obj_set_y( ui_KeyboardAntenna1, 109 );
lv_obj_set_align( ui_KeyboardAntenna1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardAntenna1, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_txtAntenaName2 = lv_textarea_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_txtAntenaName2, 338);
lv_obj_set_height( ui_txtAntenaName2, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_txtAntenaName2, -53 );
lv_obj_set_y( ui_txtAntenaName2, -120 );
lv_obj_set_align( ui_txtAntenaName2, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_txtAntenaName2,"Antenna 2");
lv_textarea_set_placeholder_text(ui_txtAntenaName2,"Placeholder...");
lv_textarea_set_one_line(ui_txtAntenaName2,true);



ui_KeyboardAntenna2 = lv_keyboard_create(ui_Antenna_Configuration);
lv_keyboard_set_mode(ui_KeyboardAntenna2,LV_KEYBOARD_MODE_TEXT_UPPER);
lv_obj_set_width( ui_KeyboardAntenna2, 720);
lv_obj_set_height( ui_KeyboardAntenna2, 179);
lv_obj_set_x( ui_KeyboardAntenna2, -14 );
lv_obj_set_y( ui_KeyboardAntenna2, 109 );
lv_obj_set_align( ui_KeyboardAntenna2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardAntenna2, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_txtAntenaName3 = lv_textarea_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_txtAntenaName3, 338);
lv_obj_set_height( ui_txtAntenaName3, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_txtAntenaName3, -53 );
lv_obj_set_y( ui_txtAntenaName3, -70 );
lv_obj_set_align( ui_txtAntenaName3, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_txtAntenaName3,"Antenna 3");
lv_textarea_set_placeholder_text(ui_txtAntenaName3,"Placeholder...");
lv_textarea_set_one_line(ui_txtAntenaName3,true);



ui_KeyboardAntenna3 = lv_keyboard_create(ui_Antenna_Configuration);
lv_keyboard_set_mode(ui_KeyboardAntenna3,LV_KEYBOARD_MODE_TEXT_UPPER);
lv_obj_set_width( ui_KeyboardAntenna3, 720);
lv_obj_set_height( ui_KeyboardAntenna3, 179);
lv_obj_set_x( ui_KeyboardAntenna3, -14 );
lv_obj_set_y( ui_KeyboardAntenna3, 109 );
lv_obj_set_align( ui_KeyboardAntenna3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardAntenna3, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_txtAntenaName4 = lv_textarea_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_txtAntenaName4, 338);
lv_obj_set_height( ui_txtAntenaName4, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_txtAntenaName4, -53 );
lv_obj_set_y( ui_txtAntenaName4, -20 );
lv_obj_set_align( ui_txtAntenaName4, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_txtAntenaName4,"Antenna 4");
lv_textarea_set_placeholder_text(ui_txtAntenaName4,"Placeholder...");
lv_textarea_set_one_line(ui_txtAntenaName4,true);



ui_KeyboardAntenna4 = lv_keyboard_create(ui_Antenna_Configuration);
lv_keyboard_set_mode(ui_KeyboardAntenna4,LV_KEYBOARD_MODE_TEXT_UPPER);
lv_obj_set_width( ui_KeyboardAntenna4, 720);
lv_obj_set_height( ui_KeyboardAntenna4, 179);
lv_obj_set_x( ui_KeyboardAntenna4, -14 );
lv_obj_set_y( ui_KeyboardAntenna4, 109 );
lv_obj_set_align( ui_KeyboardAntenna4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardAntenna4, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_lblSwitchSelector = lv_label_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_lblSwitchSelector, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblSwitchSelector, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblSwitchSelector, 209 );
lv_obj_set_y( ui_lblSwitchSelector, -170 );
lv_obj_set_align( ui_lblSwitchSelector, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblSwitchSelector,"Select switch");
lv_obj_set_style_text_color(ui_lblSwitchSelector, lv_color_hex(0x0E4ED1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblSwitchSelector, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Antenna_Configuration);
lv_obj_set_width( ui_Button3, 166);
lv_obj_set_height( ui_Button3, 33);
lv_obj_set_x( ui_Button3, 269 );
lv_obj_set_y( ui_Button3, -17 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label32 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"Save settings");

lv_obj_add_event_cb(ui_swClockEnabled, ui_event_swClockEnabled, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtWifiPassword, ui_event_txtWifiPassword, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_Keyboard2,ui_txtWifiPassword);
lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_txtAntenaName1, ui_event_txtAntenaName1, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardAntenna1,ui_txtAntenaName1);
lv_obj_add_event_cb(ui_txtAntenaName2, ui_event_txtAntenaName2, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardAntenna2,ui_txtAntenaName2);
lv_obj_add_event_cb(ui_txtAntenaName3, ui_event_txtAntenaName3, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardAntenna3,ui_txtAntenaName3);
lv_obj_add_event_cb(ui_txtAntenaName4, ui_event_txtAntenaName4, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardAntenna4,ui_txtAntenaName4);
lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
