// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "Arduino.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t* ui_Screen1;
lv_obj_t* ui_Panel2;
lv_obj_t* ui_txtTemp;
lv_obj_t* ui_Label7;
lv_obj_t* ui_Label6;
lv_obj_t* ui_Panel3;
lv_obj_t* ui_Label8;
void ui_event_btnAntena1(lv_event_t* e);
lv_obj_t* ui_btnAntena1;
lv_obj_t* ui_Label1;
void ui_event_btnAntena2(lv_event_t* e);
lv_obj_t* ui_btnAntena2;
lv_obj_t* ui_Label2;
void ui_event_btnAntena5(lv_event_t* e);
lv_obj_t* ui_btnAntena5;
lv_obj_t* ui_Label5;
void ui_event_btnAntena3(lv_event_t* e);
lv_obj_t* ui_btnAntena3;
lv_obj_t* ui_Label3;
void ui_event_btnAntena4(lv_event_t* e);
lv_obj_t* ui_btnAntena4;
lv_obj_t* ui_Label4;
lv_obj_t* ui_Panel1;
lv_obj_t* ui_xtxWifi;
lv_obj_t* ui_Image2;
void ui_event____initial_actions0(lv_event_t* e);
lv_obj_t* ui____initial_actions0;
lv_obj_t* ui_txtStatus;


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnAntena1(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_btnAntena4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    _ui_state_modify(ui_btnAntena5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    ant1Clicked(e);
  }
}
void ui_event_btnAntena2(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_btnAntena4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    _ui_state_modify(ui_btnAntena1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    ant2Clicked(e);
  }
}
void ui_event_btnAntena5(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_btnAntena1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena5, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    ant0Clicked(e);
  }
}
void ui_event_btnAntena3(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_btnAntena4, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    _ui_state_modify(ui_btnAntena1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    ant3Clicked(e);
  }
}
void ui_event_btnAntena4(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    _ui_state_modify(ui_btnAntena3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena4, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    _ui_state_modify(ui_btnAntena1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    _ui_state_modify(ui_btnAntena5, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    ant4Clicked(e);
  }
}
void ui_event____initial_actions0(lv_event_t* e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t* target = lv_event_get_target(e);
  if (event_code == LV_EVENT_SCREEN_LOAD_START) {
    ConnectWifi(e);
  }
  if (event_code == LV_EVENT_SCREEN_LOAD_START) {
    GetDataFromSwitch(e);
  }
  static uint32_t user_data = 10;
lv_timer_t * timer = lv_timer_create(my_timer, 3600,  &user_data);
}

void my_timer(lv_timer_t* timer) {
  /*Use the user_data*/
  uint32_t* user_data = timer->user_data;
  //Serial.println("my_timer called with user data: %d\n", *user_data);

  /*Do something with LVGL*/
  CollectDataFromSwitch();
  
}
///////////////////// SCREENS ////////////////////

void ui_init(void) {
  lv_disp_t* dispp = lv_disp_get_default();
  lv_theme_t* theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                            true, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_Screen1_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

  lv_disp_load_scr(ui____initial_actions0);
  lv_disp_load_scr(ui_Screen1);
}
