// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_txtTemp;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label8;
void ui_event_btnAntena1(lv_event_t * e);
extern lv_obj_t * ui_btnAntena1;
extern lv_obj_t * ui_Label1;
void ui_event_btnAntena2(lv_event_t * e);
extern lv_obj_t * ui_btnAntena2;
extern lv_obj_t * ui_Label2;
void ui_event_btnAntena5(lv_event_t * e);
extern lv_obj_t * ui_btnAntena5;
extern lv_obj_t * ui_Label5;
void ui_event_btnAntena3(lv_event_t * e);
extern lv_obj_t * ui_btnAntena3;
extern lv_obj_t * ui_Label3;
void ui_event_btnAntena4(lv_event_t * e);
extern lv_obj_t * ui_btnAntena4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_xtxWifi;
extern lv_obj_t * ui_Image2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * ui_txtStatus;
LV_IMG_DECLARE(ui_img_logo_ei9spc_png);    // assets\logo_ei9spc.png
void my_timer(lv_timer_t* timer);

LV_IMG_DECLARE(ui_img_big_squarer_png);    // assets\Big_squareR.png
LV_IMG_DECLARE(ui_img_line4_png);    // assets\line4.png
LV_IMG_DECLARE(ui_img_1861526004);    // assets\button-g2.png
LV_IMG_DECLARE(ui_img_1861550729);    // assets\button-r2.png
LV_IMG_DECLARE(ui_img_logo_png);    // assets\logo.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
